name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Login to DockerHub
        run: echo "${{ secrets.docker.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.docker.DOCKER_USERNAME }} --password-stdin
      
      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/shar_list:$(date +%s)
          docker push ${{ secrets.DOCKER_USERNAME }}/shar_list:$(date +%s)
